/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MULTIPLY = 6;
  /** RegularExpression Id. */
  int MOD = 7;
  /** RegularExpression Id. */
  int POWER = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int LT = 10;
  /** RegularExpression Id. */
  int GT = 11;
  /** RegularExpression Id. */
  int LET = 12;
  /** RegularExpression Id. */
  int GET = 13;
  /** RegularExpression Id. */
  int NEQ = 14;
  /** RegularExpression Id. */
  int assignment = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int NUM = 17;
  /** RegularExpression Id. */
  int END = 18;
  /** RegularExpression Id. */
  int FLOOP = 19;
  /** RegularExpression Id. */
  int WLOOP = 20;
  /** RegularExpression Id. */
  int LP = 21;
  /** RegularExpression Id. */
  int RP = 22;
  /** RegularExpression Id. */
  int FUNCTION = 23;
  /** RegularExpression Id. */
  int Return = 24;
  /** RegularExpression Id. */
  int FLOATINGPOINT = 25;
  /** RegularExpression Id. */
  int DOUBLE = 26;
  /** RegularExpression Id. */
  int LETTER = 27;
  /** RegularExpression Id. */
  int VAR = 28;
  /** RegularExpression Id. */
  int IF = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int READ = 31;
  /** RegularExpression Id. */
  int WRITE = 32;
  /** RegularExpression Id. */
  int COLON = 33;
  /** RegularExpression Id. */
  int SIMICOLON = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<PLUS>",
    "<MULTIPLY>",
    "\"%\"",
    "\"^\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "<LET>",
    "<GET>",
    "<NEQ>",
    "<assignment>",
    "<DIGIT>",
    "<NUM>",
    "\"!\"",
    "\"&\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "\"func\"",
    "\"return\"",
    "<FLOATINGPOINT>",
    "<DOUBLE>",
    "<LETTER>",
    "<VAR>",
    "\"?\"",
    "\"??\"",
    "\"<-\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
  };

}
