/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MULTIPLY = 6;
  /** RegularExpression Id. */
  int POWER = 7;
  /** RegularExpression Id. */
  int EQ = 8;
  /** RegularExpression Id. */
  int LT = 9;
  /** RegularExpression Id. */
  int GT = 10;
  /** RegularExpression Id. */
  int LET = 11;
  /** RegularExpression Id. */
  int GET = 12;
  /** RegularExpression Id. */
  int NEQ = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int assignment = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int NUM = 19;
  /** RegularExpression Id. */
  int END = 20;
  /** RegularExpression Id. */
  int FLOOP = 21;
  /** RegularExpression Id. */
  int WLOOP = 22;
  /** RegularExpression Id. */
  int LP = 23;
  /** RegularExpression Id. */
  int RP = 24;
  /** RegularExpression Id. */
  int FUNCTION = 25;
  /** RegularExpression Id. */
  int DEF = 26;
  /** RegularExpression Id. */
  int DATA = 27;
  /** RegularExpression Id. */
  int FLOATINGPOINT = 28;
  /** RegularExpression Id. */
  int DOUBLE = 29;
  /** RegularExpression Id. */
  int LETTER = 30;
  /** RegularExpression Id. */
  int VAR = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int ELSE = 33;
  /** RegularExpression Id. */
  int READ = 34;
  /** RegularExpression Id. */
  int WRITE = 35;
  /** RegularExpression Id. */
  int COLON = 36;
  /** RegularExpression Id. */
  int SIMICOLON = 37;
  /** RegularExpression Id. */
  int Quotation = 38;
  /** RegularExpression Id. */
  int DQuotation = 39;
  /** RegularExpression Id. */
  int STRING = 40;
  /** RegularExpression Id. */
  int CHAR = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<PLUS>",
    "<MULTIPLY>",
    "\"^\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "<LET>",
    "<GET>",
    "<NEQ>",
    "\"|\"",
    "\"$\"",
    "\"~\"",
    "<assignment>",
    "<DIGIT>",
    "<NUM>",
    "\"!\"",
    "\"&\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "\"func\"",
    "\"def\"",
    "<DATA>",
    "<FLOATINGPOINT>",
    "<DOUBLE>",
    "<LETTER>",
    "<VAR>",
    "\"?\"",
    "\"??\"",
    "\"<-\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<STRING>",
    "<CHAR>",
    "\",\"",
  };

}
